id: "logistic_regression"
display_name: "Logistic Regression"

definition:
  _target_: sklearn.linear_model.LogisticRegression
  penalty: "l2"
  dual: False 
  tol: 0.0001
  C: 1.0 
  fit_intercept: True
  intercept_scaling: 1
  max_iter: 1000