display_name: "Logistic Regression"

definition:
  _target_: sklearn.linear_model.LogisticRegression
  penalty: "l2"
  fit_intercept: True # learn bias term
  class_weight: "balanced"
  tol: 1e-6
  C: 100.0 
  max_iter: 10000
  dual: False 
  intercept_scaling: 1
