defaults:
  - dataset: digits_toy
  - embedding: dino_adapter
  - prequery: null
  - query_strategy: random_sampling
  - _self_

# Dont add model to default list to not have to override it.
model: null
random_seed: 0

