defaults:
  - dataset: digits_toy
  - adapter: dino_adapter
  - prequery: null
  - query_strategy: random_sampling
  - _self_

# TODO maybe checking if key is not there is easier.
# Dont add model to default list to not have to override it.
model: null
random_seed: 0

