display_name: "all-mpnet-base-v2"

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Text]

definition:
  _target_: skactiveml_annotation.embedding.sentence_transformer.SentenceTransformerAdapter
  model_variant: "all-mpnet-base-v2"
