display_name: "DINOv2 small 384"

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Image]

definition:
  _target_: skactiveml_annotation.embedding.dino.TorchVisionAdapter
  model_variant: "dinov2_vits14"
  batch_size: 8 # TODO remove batch_size from here and let the user set it the the UI.
