display_name: "DINOv2 base 768"

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Image]

definition:
  _target_: embedding.dino.TorchVisionAdapter
  model_variant: "dinov2_vitb14"
  batch_size: 8
