display_name: "Basic Flatten Image"

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Image]

definition:
  _target_: skactiveml_annotation.embedding.basic_flatten.SimpleFlattenAdapter

