id: "cifar10_tiny"
display_name: "CIFAR-10 Tiny"
label_names: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
data_path: 'cifar10_small_images'

data_type:
  _target_: core.schema.DataType
  _args_: [Image]

preprocessor:
  _target_: core.adapter.SimpleFlattenAdapter
