display_name: "CIFAR-100"
classes: [
  'apples', 'aquarium fish', 'baby', 'bear', 'beaver', 'bed', 'bee', 'beetle', 'bicycle',
  'bottles', 'bowls', 'boy', 'bridge', 'bus', 'butterfly', 'camel', 'cans', 'castle',
  'caterpillar', 'cattle', 'chair', 'chimpanzee', 'clock', 'cloud', 'cockroach',
  'computer keyboard', 'couch', 'crab', 'crocodile', 'cups', 'dinosaur', 'dolphin',
  'elephant', 'flatfish', 'forest', 'fox', 'girl', 'hamster', 'house', 'kangaroo',
  'lamp', 'lawn-mower', 'leopard', 'lion', 'lizard', 'lobster', 'man', 'maple',
  'motorcycle', 'mountain', 'mouse', 'mushrooms', 'oak', 'oranges', 'orchid', 'otter',
  'palm', 'pears', 'pickup truck', 'pine', 'plain', 'plates', 'poppies', 'porcupine',
  'possum', 'rabbit', 'raccoon', 'ray', 'road', 'rocket', 'roses', 'sea', 'seal',
  'shark', 'shrew', 'skunk', 'skyscraper', 'snail', 'snake', 'spider', 'squirrel',
  'streetcar', 'sunflowers', 'sweet peppers', 'table', 'tank', 'telephone',
  'television', 'tiger', 'tractor', 'train', 'trout', 'tulips', 'turtle', 'wardrobe',
  'whale', 'willow', 'wolf', 'woman', 'worm'
]
data_path: 'datasets/cifar100/cifar100_images'

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Image]
