id: "cifar10"
display_name: "CIFAR-10"
label_names: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
data_path: 'cifar10_images'

data_type:
  _target_: core.schema.DataType
  _args_: [Image]

preprocessor:
  _target_: core.adapter.SimpleFlattenAdapter

embedding:
  _target_:


transforms:
  _target_:

train_params:
  train: True
eval_params:
  train: False 
num_workers: 4
dataloader_batch_size: 32
n_classes: 10