id: "digits_toy"
display_name: "Handwritten Digits 8x8"
label_names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
data_path: 'digits_images'

data_type:
  _target_: core.schema.DataType
  _args_: [Image]


