display_name: "Handwritten Digits 8x8"
classes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
data_path: 'datasets/digits_images'

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Image]


