display_name: "IMDB Movie Reviews"
classes: ['positive', 'negative']
data_path: 'datasets/raw_text/imdb/imdb_texts'

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Text]
