id: "mnist"
display_name: "MNIST (28 x 28)"
classes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
data_path: 'datasets/mnist/mnist_images'

data_type:
  _target_: core.schema.DataType
  _args_: [Image]