display_name: "STL-10"
classes: ['airplane', 'bird', 'car', 'cat', 'deer', 'dog', 'horse', 'monkey', 'ship', 'truck']
data_path: 'datasets/stl10/stl10_images'

data_type:
  _target_: skactiveml_annotation.core.schema.DataType
  _args_: [Image]
