name: "cifar10"

data_type: 
  _target_: core.schema.DataType
  _args_: [Image]

raw_data:
  _target_: torchvision.datasets.CIFAR10
  train: True
  download: True
  test_size: 0.3

train_params:
  train: True
eval_params:
  train: False 
num_workers: 4
dataloader_batch_size: 32
n_classes: 10