name: "lfw"
display_name: "Labeled Faces in the Wild"

n_classes: 5749

data_type: 
  _target_: core.schema.DataType
  _args_: [Image]

adapter_cfg:
  _target_: core.adapters.SklearnImageDataAdapter
  dataloader:
    _target_: sklearn.datasets.fetch_lfw_people
    color: True
    return_X_y: False

raw_data:
  _target_: sklearn.datasets.fetch_lfw_people
  return_X_y: True
