name: "olivetti_faces"

data_type: 
  _target_: src.core.schema.DataType
  _args_: Image
  
raw_data:
  _target_: sklearn.datasets.fetch_olivetti_faces
  return_X_y: True

human_adapter:
  _target_: sklearn.datasets.fetch_olivetti_faces

train_params:
  train: True
eval_params:
  train: False 
num_workers: 4
dataloader_batch_size: 32
n_classes: 10