id: "dino_adapter"
display_name: "Dino Adapter vitb14"

data_type:
  _target_: core.schema.DataType
  _args_: [Image]

definition:
  _target_: core.adapter.TorchVisionAdapter
  model_variant: "dinov2_vitb14"
  batch_size: 8 # TODO remove batch_size from here and let the user set it the the UI.
